#include "shared-bindings/board/__init__.h"

STATIC const mp_rom_map_elem_t board_module_globals_table[] = {
    { MP_ROM_QSTR(MP_QSTR_M1_DIR_A),   MP_ROM_PTR(&pin_P1_10) },
    { MP_ROM_QSTR(MP_QSTR_M1_DIR_B),   MP_ROM_PTR(&pin_P1_11) },
    { MP_ROM_QSTR(MP_QSTR_M2_DIR_A),   MP_ROM_PTR(&pin_P1_12) },
    { MP_ROM_QSTR(MP_QSTR_M2_DIR_B),   MP_ROM_PTR(&pin_P1_13) },
    { MP_ROM_QSTR(MP_QSTR_STAT_DOUT),  MP_ROM_PTR(&pin_P1_05) },
    { MP_ROM_QSTR(MP_QSTR_RGB_DOUT),   MP_ROM_PTR(&pin_P1_07) },
    { MP_ROM_QSTR(MP_QSTR_M1_E_A),     MP_ROM_PTR(&pin_P0_27) },
    { MP_ROM_QSTR(MP_QSTR_M1_E_B),     MP_ROM_PTR(&pin_P0_26) },
    { MP_ROM_QSTR(MP_QSTR_M2_E_A),     MP_ROM_PTR(&pin_P0_14) },
    { MP_ROM_QSTR(MP_QSTR_M2_E_B),     MP_ROM_PTR(&pin_P0_12) },
    { MP_ROM_QSTR(MP_QSTR_LED_EN),     MP_ROM_PTR(&pin_P1_06) },
    { MP_ROM_QSTR(MP_QSTR_TOF1_INT),   MP_ROM_PTR(&pin_P0_06) },
    { MP_ROM_QSTR(MP_QSTR_TOF2_INT),   MP_ROM_PTR(&pin_P0_08) },
    { MP_ROM_QSTR(MP_QSTR_TOF3_INT),   MP_ROM_PTR(&pin_P1_09) },
    { MP_ROM_QSTR(MP_QSTR_TOF1_EN),    MP_ROM_PTR(&pin_P0_07) },
    { MP_ROM_QSTR(MP_QSTR_TOF2_EN),    MP_ROM_PTR(&pin_P1_08) },
    { MP_ROM_QSTR(MP_QSTR_TOF3_EN),    MP_ROM_PTR(&pin_P0_11) },
    { MP_ROM_QSTR(MP_QSTR_BATT_LVL1),  MP_ROM_PTR(&pin_P0_10) },
    { MP_ROM_QSTR(MP_QSTR_BATT_LVL2),  MP_ROM_PTR(&pin_P0_09) },
    { MP_ROM_QSTR(MP_QSTR_BATT_LVL3),  MP_ROM_PTR(&pin_P1_00) },
    { MP_ROM_QSTR(MP_QSTR_BATT_LVL4),  MP_ROM_PTR(&pin_P0_22) },
    { MP_ROM_QSTR(MP_QSTR_HOST_INT_1), MP_ROM_PTR(&pin_P0_15) },
    { MP_ROM_QSTR(MP_QSTR_HOST_INT_2), MP_ROM_PTR(&pin_P0_17) },
    { MP_ROM_QSTR(MP_QSTR_IMU_INT),    MP_ROM_PTR(&pin_P1_01) },
    { MP_ROM_QSTR(MP_QSTR_IMU_RESET),  MP_ROM_PTR(&pin_P1_03) },
    { MP_ROM_QSTR(MP_QSTR_M1_PWM),     MP_ROM_PTR(&pin_P1_14) },
    { MP_ROM_QSTR(MP_QSTR_M2_PWM),     MP_ROM_PTR(&pin_P1_15) },
    { MP_ROM_QSTR(MP_QSTR_BUZZER),     MP_ROM_PTR(&pin_P1_04) },
    { MP_ROM_QSTR(MP_QSTR_SERVO_PWM),  MP_ROM_PTR(&pin_P1_02) },
    { MP_ROM_QSTR(MP_QSTR_IR1),        MP_ROM_PTR(&pin_P0_02) },
    { MP_ROM_QSTR(MP_QSTR_IR2),        MP_ROM_PTR(&pin_P0_03) },
    { MP_ROM_QSTR(MP_QSTR_IR3),        MP_ROM_PTR(&pin_P0_04) },
    { MP_ROM_QSTR(MP_QSTR_IR4),        MP_ROM_PTR(&pin_P0_05) },
    { MP_ROM_QSTR(MP_QSTR_IR5),        MP_ROM_PTR(&pin_P0_28) },
    { MP_ROM_QSTR(MP_QSTR_V_DIV_BATT), MP_ROM_PTR(&pin_P0_29) },
    { MP_ROM_QSTR(MP_QSTR_MIC),        MP_ROM_PTR(&pin_P0_30) },
    { MP_ROM_QSTR(MP_QSTR_SDA),        MP_ROM_PTR(&pin_P0_25) },
    { MP_ROM_QSTR(MP_QSTR_SCL),        MP_ROM_PTR(&pin_P0_24) },
    { MP_ROM_QSTR(MP_QSTR_SDA_PERIPH), MP_ROM_PTR(&pin_P0_16) },
    { MP_ROM_QSTR(MP_QSTR_SCL_PERIPH), MP_ROM_PTR(&pin_P0_13) },
    { MP_ROM_QSTR(MP_QSTR_F_MISO),     MP_ROM_PTR(&pin_P0_19) },
    { MP_ROM_QSTR(MP_QSTR_F_SCK),      MP_ROM_PTR(&pin_P0_20) },
    { MP_ROM_QSTR(MP_QSTR_F_MOSI),     MP_ROM_PTR(&pin_P0_21) },
    { MP_ROM_QSTR(MP_QSTR_F_CS),       MP_ROM_PTR(&pin_P0_23) },
    { MP_ROM_QSTR(MP_QSTR_SPI), MP_ROM_PTR(&board_spi_obj) },
    { MP_ROM_QSTR(MP_QSTR_I2C), MP_ROM_PTR(&board_i2c_obj) },
};

MP_DEFINE_CONST_DICT(board_module_globals, board_module_globals_table);
